production:
  daily_crawl_vira:
    class: CrawlViraJob
    queue: background
    args: []
    schedule: at 1am every day
  daily_send_wechat_group:
    class: SendWechatGroupJob
    queue: background
    args: []
    schedule: at 8:30am every day
  daily_check_vira_token:
    class: CheckViraTokenJob
    queue: background
    args: []
    schedule: at 1am every day
